# Generated by Django 3.0.3 on 2020-03-28 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPeriodicChange', models.BooleanField(default=False)),
                ('passMinLength', models.PositiveIntegerField(default=8)),
                ('passMaxLength', models.PositiveIntegerField(blank=True, null=True)),
                ('needUppercase', models.BooleanField(default=False)),
                ('needLowercase', models.BooleanField(default=False)),
                ('needSpecialChar', models.BooleanField(default=False)),
                ('needNumericChar', models.BooleanField(default=False)),
                ('cannotUsePreviousPass', models.BooleanField(default=False)),
                ('numberOfAttemps', models.PositiveIntegerField(default=3)),
                ('delayBetweenAttemps', models.PositiveIntegerField(default=1)),
                ('contactAdminAfterFailure', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isEmailConfirmed', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Administrateur', 'Administrateur'), ('Proposé aux clients résidentiels', 'Proposé aux clients résidentiels'), ("Proposé aux clients clients d'affaire", "Proposé aux clients clients d'affaire")], max_length=37)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
