# Generated by Django 3.0.4 on 2020-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab5', '0002_auto_20200329_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='cannotUsePreviousPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='params',
            name='contactAdminAfterFailure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='params',
            name='delayBetweenAttemps',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='params',
            name='isPeriodicChange',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='params',
            name='needLowercase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='params',
            name='needNumericChar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='params',
            name='needSpecialChar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='params',
            name='needUppercase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='params',
            name='numberOfAttemps',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='params',
            name='passMaxLength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='params',
            name='passMinLength',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
