# Generated by Django 3.0.5 on 2020-04-02 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lab5', '0003_auto_20200329_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.CharField(max_length=2)),
                ('key2', models.CharField(max_length=2)),
                ('key3', models.CharField(max_length=2)),
                ('value1', models.CharField(max_length=1)),
                ('value2', models.CharField(max_length=1)),
                ('value3', models.CharField(max_length=1)),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
